### ISSUE TITLE
No Option to start a Tabs project without Typescript

### ISSUE THREAD

**Issue by jennifer-elyse** [react-native-community/.github#74]
# Feature request

## Why it is needed
No one should be forced into using Typescript and the tabs project is a nice way to start. Starting out, I found the tabs project essential to learning and I'm sure others would benefit from it. To force someone to use Typescript is an unfair disadvantage whether they aren't interested in using it in general or are new to Javascript.

It used to be available

**Comment by mikehardy** [comment]
Hello!
Typescript and javascript are interoperable, I don't think it's technically possible to force someone to use anything.
There is no link provided, so I'm not sure what project you are talking about - this for instance is neither the react-native-community nor typescript: https://www.npmjs.com/package/react-native-tabs

react-native-webview is an example of a project using typescript and kotlin for instance, but there is no requirement to use typescript in order to use the library.

react-native-device-info is also in typescript, but no problem. We ship it with .js files built out.

Now, if you are talking as a contributing developer - the language a module is implemented in is a maintainer decision. And if you want to contribute, then yes, it's "forced" in the same way you go to a class and the professor "forces" you to use their chosen textbook. If that's disagreeable - take a different class / use a different module
